# Generated by model-architect subagent via /build command.
# Expected modules:
#   configs.py   — MODEL_CONFIGS: dict[str, dict]
#   trainer.py   — train_all(X_train, y_train, X_test, y_test) -> dict
