# Generated by data-analyst subagent via /analyze command.
# Expected modules:
#   analysis.py  — summarize_dataset(), find_top_features(), detect_task_type()
#   plots.py     — plot_distributions(), plot_correlation_heatmap()
